name: infinityCRM
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:


  flutter:
    sdk: flutter
  intl: ^0.18.0
  url_launcher: ^6.1.7
  image_picker: ^0.8.7+3
  lucide_icons: ^0.144.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  font_awesome_flutter: ^10.3.0
  table_calendar: ^3.0.9
  # Chat Bubbles
  chat_bubbles: 1.5.0 # For modern and customizable chat bubbles
  flutter_vector_icons: ^2.0.0
  provider: ^6.0.5  # Use the latest version available on pub.dev
  flutter_animate: ^4.3.0  # Use the latest version available on pub.dev



dev_dependencies:
  flutter_launcher_icons: ^0.13.1


  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  rename: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/infinityCRM.png"


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/flags/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Black.ttf
          weight: 900
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lexend-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lexend-Light.ttf
          weight: 300
        - asset: assets/fonts/Lexend-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lexend-Thin.ttf
          weight: 100



    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF/SFProDisplayBlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/SF/SFProDisplayBold.otf
          weight: 700
        - asset: assets/fonts/SF/SFProDisplayHeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF/SFProDisplayLightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF/SFProDisplayMedium.otf
          weight: 500
        - asset: assets/fonts/SF/SFProDisplayRegular.otf
          weight: 400
        - asset: assets/fonts/SF/SFProDisplaySemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SF/SFProDisplayThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/SF/SFProDisplayUltraLightItalic.otf
          weight: 200
          style: italic
